version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db

  test:
    build:
      context: .
    command: ["pytest"]
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=testing
      - DATABASE_URL=sqlite:///app.db
